from __future__ import annotations

from dataclasses import dataclass
from typing import Literal

import torch


ActivationOffload = Literal["none", "cpu"]
ActivationQuant = Literal["none", "int8"]


@dataclass
class _PackedTensor:
    mode: Literal["gpu", "cpu", "int8"]
    dtype: torch.dtype
    device: torch.device
    shape: torch.Size
    tensor: torch.Tensor | None = None
    scale: torch.Tensor | None = None
    ready_event: torch.cuda.Event | None = None

    @property
    def nbytes(self) -> int:
        total = 0
        if self.tensor is not None:
            total += self.tensor.numel() * self.tensor.element_size()
        if self.scale is not None:
            total += self.scale.numel() * self.scale.element_size()
        return total


@dataclass
class RWKV7ActivationCheckpoint:
    hidden: _PackedTensor
    has_v_first: bool


def _empty_cpu(shape: torch.Size, dtype: torch.dtype, pin_memory: bool) -> torch.Tensor:
    try:
        return torch.empty(shape, dtype=dtype, device="cpu", pin_memory=pin_memory)
    except RuntimeError:
        return torch.empty(shape, dtype=dtype, device="cpu")


class RWKV7ActivationStore:
    """Activation checkpoint store specialized for RWKV-7 replay.

    `v_first` is generated by layer 0 and reused by all later layers. The store
    therefore saves it once per batch and lets checkpoints keep only a handle.
    """

    def __init__(self, offload: ActivationOffload = "none", quant: ActivationQuant = "none"):
        if offload not in ("none", "cpu"):
            raise ValueError("activation_offload must be 'none' or 'cpu'")
        if quant not in ("none", "int8"):
            raise ValueError("activation_quant must be 'none' or 'int8'")
        if quant == "int8" and offload != "cpu":
            raise ValueError("activation_quant='int8' requires activation_offload='cpu'")
        self.offload = offload
        self.quant = quant
        self._v_first: _PackedTensor | None = None
        self._v_first_gpu_cache: dict[tuple[torch.device, torch.dtype], torch.Tensor] = {}
        self.offloaded_bytes = 0

    def clear(self) -> None:
        self._v_first = None
        self._v_first_gpu_cache.clear()
        self.offloaded_bytes = 0

    def save_v_first(self, v_first: torch.Tensor) -> None:
        if self._v_first is None:
            self._v_first = self._pack(v_first)
            self.offloaded_bytes += self._v_first.nbytes

    def checkpoint(self, hidden: torch.Tensor, has_v_first: bool) -> RWKV7ActivationCheckpoint:
        packed_hidden = self._pack(hidden)
        self.offloaded_bytes += packed_hidden.nbytes
        return RWKV7ActivationCheckpoint(hidden=packed_hidden, has_v_first=has_v_first)

    def unpack(self, checkpoint: RWKV7ActivationCheckpoint, device: torch.device) -> tuple[torch.Tensor, torch.Tensor]:
        hidden = self._unpack(checkpoint.hidden, device)
        if not checkpoint.has_v_first:
            return hidden, torch.empty_like(hidden)
        if self._v_first is None:
            raise RuntimeError("v_first checkpoint handle was requested before v_first was saved")
        key = (device, self._v_first.dtype)
        cached = self._v_first_gpu_cache.get(key)
        if cached is None:
            cached = self._unpack(self._v_first, device)
            self._v_first_gpu_cache[key] = cached
        return hidden, cached

    def _pack(self, tensor: torch.Tensor) -> _PackedTensor:
        detached = tensor.detach()
        if self.offload == "none":
            return _PackedTensor(
                mode="gpu",
                dtype=detached.dtype,
                device=detached.device,
                shape=detached.shape,
                tensor=detached,
            )

        if self.quant == "int8":
            payload, scale = self._quantize_int8(detached)
            event = _record_ready_event(detached.device) if detached.is_cuda else None
            return _PackedTensor(
                mode="int8",
                dtype=detached.dtype,
                device=detached.device,
                shape=detached.shape,
                tensor=payload,
                scale=scale,
                ready_event=event,
            )

        cpu = _empty_cpu(detached.shape, detached.dtype, pin_memory=detached.is_cuda)
        cpu.copy_(detached, non_blocking=detached.is_cuda)
        if detached.is_cuda:
            detached.record_stream(torch.cuda.current_stream(detached.device))
        event = _record_ready_event(detached.device) if detached.is_cuda else None
        return _PackedTensor(
            mode="cpu",
            dtype=detached.dtype,
            device=detached.device,
            shape=detached.shape,
            tensor=cpu,
            ready_event=event,
        )

    def _unpack(self, packed: _PackedTensor, device: torch.device) -> torch.Tensor:
        _wait_ready_event(packed, device)
        if packed.mode == "gpu":
            assert packed.tensor is not None
            return packed.tensor.to(device=device, dtype=packed.dtype, non_blocking=True)
        if packed.mode == "cpu":
            assert packed.tensor is not None
            return packed.tensor.to(device=device, dtype=packed.dtype, non_blocking=True)

        assert packed.tensor is not None
        assert packed.scale is not None
        q = packed.tensor.to(device=device, non_blocking=True).float()
        scale = packed.scale.to(device=device, non_blocking=True).float()
        return (q * scale).to(dtype=packed.dtype)

    def _quantize_int8(self, tensor: torch.Tensor) -> tuple[torch.Tensor, torch.Tensor]:
        values = tensor.detach().float()
        scale = values.abs().amax(dim=-1, keepdim=True).clamp_min(1e-8) / 127.0
        quantized = torch.clamp(torch.round(values / scale), -127, 127).to(torch.int8)

        q_cpu = _empty_cpu(quantized.shape, torch.int8, pin_memory=tensor.is_cuda)
        s_cpu = _empty_cpu(scale.shape, torch.float16, pin_memory=tensor.is_cuda)
        q_cpu.copy_(quantized, non_blocking=tensor.is_cuda)
        s_cpu.copy_(scale.to(torch.float16), non_blocking=tensor.is_cuda)
        if tensor.is_cuda:
            quantized.record_stream(torch.cuda.current_stream(tensor.device))
            scale.record_stream(torch.cuda.current_stream(tensor.device))
        return q_cpu, s_cpu


def _record_ready_event(device: torch.device) -> torch.cuda.Event:
    event = torch.cuda.Event(enable_timing=False)
    event.record(torch.cuda.current_stream(device))
    return event


def _wait_ready_event(packed: _PackedTensor, device: torch.device) -> None:
    if packed.ready_event is not None and device.type == "cuda":
        torch.cuda.current_stream(device).wait_event(packed.ready_event)
